/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bot.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/bot.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Bot" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Alpha_Joints" geometry={nodes.Alpha_Joints.geometry} material={materials.Alpha_Joints_MAT} skeleton={nodes.Alpha_Joints.skeleton} />
          <skinnedMesh name="Alpha_Surface" geometry={nodes.Alpha_Surface.geometry} material={materials.Alpha_Body_MAT} skeleton={nodes.Alpha_Surface.skeleton} />
          <skinnedMesh name="HeadCollider" geometry={nodes.HeadCollider.geometry} material={nodes.HeadCollider.material} skeleton={nodes.HeadCollider.skeleton} />
          <skinnedMesh name="HipsCollider" geometry={nodes.HipsCollider.geometry} material={nodes.HipsCollider.material} skeleton={nodes.HipsCollider.skeleton} />
          <skinnedMesh name="LeftArmCollider" geometry={nodes.LeftArmCollider.geometry} material={nodes.LeftArmCollider.material} skeleton={nodes.LeftArmCollider.skeleton} />
          <skinnedMesh name="LeftForeArmCollider" geometry={nodes.LeftForeArmCollider.geometry} material={nodes.LeftForeArmCollider.material} skeleton={nodes.LeftForeArmCollider.skeleton} />
          <skinnedMesh name="LeftLegCollider" geometry={nodes.LeftLegCollider.geometry} material={nodes.LeftLegCollider.material} skeleton={nodes.LeftLegCollider.skeleton} />
          <skinnedMesh name="LeftUpLegCollider" geometry={nodes.LeftUpLegCollider.geometry} material={nodes.LeftUpLegCollider.material} skeleton={nodes.LeftUpLegCollider.skeleton} />
          <skinnedMesh name="RightArmCollider" geometry={nodes.RightArmCollider.geometry} material={nodes.RightArmCollider.material} skeleton={nodes.RightArmCollider.skeleton} />
          <skinnedMesh name="RightForeArmCollider" geometry={nodes.RightForeArmCollider.geometry} material={nodes.RightForeArmCollider.material} skeleton={nodes.RightForeArmCollider.skeleton} />
          <skinnedMesh name="RightLegCollider" geometry={nodes.RightLegCollider.geometry} material={nodes.RightLegCollider.material} skeleton={nodes.RightLegCollider.skeleton} />
          <skinnedMesh name="RightUpLegCollider" geometry={nodes.RightUpLegCollider.geometry} material={nodes.RightUpLegCollider.material} skeleton={nodes.RightUpLegCollider.skeleton} />
          <skinnedMesh name="TorsoCollider" geometry={nodes.TorsoCollider.geometry} material={nodes.TorsoCollider.material} skeleton={nodes.TorsoCollider.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bot.glb')
